import { CASE_SLUGS, LOCALES, type Locale } from '../content'

/**
 * Every URL the site owns is built here. Path segments are localised (`proyectos`
 * vs `work`) but slugs are not, so the two locales stay one-to-one and hreflang
 * can be generated by swapping the locale.
 */

const CASE_SEGMENT: Record<Locale, string> = {
  es: 'proyectos',
  en: 'work',
}

export const homePath = (locale: Locale) => `/${locale}`

export const casePath = (locale: Locale, slug: string) =>
  `/${locale}/${CASE_SEGMENT[locale]}/${slug}`

export const cvPath = (locale: Locale) => `/${locale}/cv`

export const NOT_FOUND_PATH = '/404'

export const LOCALE_GATE_PATH = '/'

/** Anchors inside the single-page home. */
export const SECTION_IDS = [
  'hero',
  'work',
  'experience',
  'services',
  'process',
  'about',
  'contact',
] as const

export type SectionId = (typeof SECTION_IDS)[number]

export const sectionPath = (locale: Locale, id: SectionId) =>
  `${homePath(locale)}#${id}`

/**
 * The full prerender manifest. `react-router.config.ts` and the sitemap both
 * read this, so a new route cannot be indexed without also being built.
 */
export const staticPaths = (): string[] => [
  LOCALE_GATE_PATH,
  NOT_FOUND_PATH,
  ...LOCALES.flatMap((locale) => [
    homePath(locale),
    cvPath(locale),
    ...CASE_SLUGS.map((slug) => casePath(locale, slug)),
  ]),
]

/** Same path in the other locale, used for hreflang and the language switch. */
export const translatePath = (path: string, target: Locale): string => {
  const segments = path.replace(/^\/+|\/+$/g, '').split('/')
  const [current, ...rest] = segments

  if (!LOCALES.includes(current as Locale)) return `/${target}`
  if (rest.length === 0) return homePath(target)

  const [section, slug] = rest
  if (section === 'cv') return cvPath(target)
  if (slug && (section === CASE_SEGMENT.es || section === CASE_SEGMENT.en)) {
    return casePath(target, slug)
  }
  return homePath(target)
}
