import { livePowerFor, sceneState } from '../scene/sceneState'

/**
 * The reactor's sound, synthesised rather than downloaded.
 *
 * Shipping room tone and transients as audio files would have cost a couple of
 * hundred kilobytes for a layer most visitors never turn on. Everything here is
 * generated by Web Audio instead: two detuned oscillators through a low-pass for the
 * room, filtered noise for a module locking into place, and a resolving interval at
 * ignition. Zero bytes of assets, and the tone can follow the charge value directly.
 *
 * Rules this module keeps:
 * - Nothing is created until the visitor asks for it. Browsers block audio without a
 *   gesture, and starting a context on load would be hostile even where it is allowed.
 * - It is independent of `prefers-reduced-motion`. Someone who cannot tolerate motion
 *   may still want sound, and vice versa; conflating the two takes a choice away.
 * - A hidden tab is silent, and the whole graph is torn down on opt-out.
 */

/** Deliberately low: this is a room, not a soundtrack. */
const ROOM_GAIN = 0.035
const IGNITION_GAIN = 0.05

export interface ReactorSound {
  stop: () => void
  /** Called when a module locks into place. */
  pulse: () => void
}

const noiseBuffer = (context: AudioContext): AudioBuffer => {
  const length = Math.floor(context.sampleRate * 0.4)
  const buffer = context.createBuffer(1, length, context.sampleRate)
  const data = buffer.getChannelData(0)
  for (let index = 0; index < length; index += 1) {
    // Decaying white noise: the envelope is baked in so a transient needs no
    // scheduled gain ramp of its own.
    const decay = 1 - index / length
    data[index] = (Math.random() * 2 - 1) * decay * decay
  }
  return buffer
}

export const startReactorSound = (): ReactorSound => {
  const context = new AudioContext()

  const master = context.createGain()
  master.gain.value = 0
  master.connect(context.destination)

  // Room tone: a low fifth, slightly detuned so it beats rather than sits still.
  const room = context.createGain()
  room.gain.value = ROOM_GAIN
  const roomFilter = context.createBiquadFilter()
  roomFilter.type = 'lowpass'
  roomFilter.frequency.value = 220
  roomFilter.Q.value = 0.6
  room.connect(roomFilter).connect(master)

  const drones = [55, 82.5].map((frequency, index) => {
    const oscillator = context.createOscillator()
    oscillator.type = 'sine'
    oscillator.frequency.value = frequency
    oscillator.detune.value = index === 0 ? -4 : 6
    const gain = context.createGain()
    gain.gain.value = index === 0 ? 1 : 0.45
    oscillator.connect(gain).connect(room)
    oscillator.start()
    return { oscillator, gain }
  })

  // A very slow swell so the room breathes instead of humming flat.
  const breath = context.createOscillator()
  breath.type = 'sine'
  breath.frequency.value = 0.07
  const breathDepth = context.createGain()
  breathDepth.gain.value = ROOM_GAIN * 0.4
  breath.connect(breathDepth).connect(room.gain)
  breath.start()

  // Ignition: a fifth above the drone, opened only by the final chapter.
  const ignition = context.createGain()
  ignition.gain.value = 0
  ignition.connect(master)
  const ignitionVoice = context.createOscillator()
  ignitionVoice.type = 'triangle'
  ignitionVoice.frequency.value = 165
  ignitionVoice.connect(ignition)
  ignitionVoice.start()

  const noise = noiseBuffer(context)

  // Fade in, so switching sound on is not a click.
  master.gain.linearRampToValueAtTime(1, context.currentTime + 0.9)

  let frame = 0
  const follow = () => {
    const power = livePowerFor(sceneState.build)
    const now = context.currentTime
    // `setTargetAtTime` smooths automatically, so scroll velocity cannot produce
    // zipper noise on the filter.
    roomFilter.frequency.setTargetAtTime(220 + sceneState.build * 260, now, 0.3)
    ignition.gain.setTargetAtTime(power * IGNITION_GAIN, now, 0.4)
    frame = requestAnimationFrame(follow)
  }
  frame = requestAnimationFrame(follow)

  const handleVisibility = () => {
    if (document.visibilityState === 'hidden') {
      void context.suspend()
      return
    }
    void context.resume()
  }
  document.addEventListener('visibilitychange', handleVisibility)

  return {
    pulse: () => {
      if (context.state !== 'running') return
      const source = context.createBufferSource()
      source.buffer = noise
      const band = context.createBiquadFilter()
      band.type = 'bandpass'
      band.frequency.value = 880
      band.Q.value = 1.4
      const gain = context.createGain()
      gain.gain.value = 0.06
      source.connect(band).connect(gain).connect(master)
      source.start()
    },
    stop: () => {
      cancelAnimationFrame(frame)
      document.removeEventListener('visibilitychange', handleVisibility)
      master.gain.setTargetAtTime(0, context.currentTime, 0.15)
      // Let the fade finish before tearing the graph down, otherwise stopping
      // produces the click that fading in was there to avoid.
      window.setTimeout(() => {
        drones.forEach(({ oscillator }) => oscillator.stop())
        breath.stop()
        ignitionVoice.stop()
        void context.close()
      }, 400)
    },
  }
}
