import { liveLaw, reactorControl } from '../scene/control/reactorControl'
import { livePowerFor, sceneState } from '../scene/sceneState'

/**
 * The reactor's sound, synthesised rather than downloaded.
 *
 * Shipping room tone and transients as audio files would have cost a couple of
 * hundred kilobytes for a layer most visitors never turn on. Everything here is
 * generated by Web Audio instead: two detuned oscillators through a low-pass for
 * the room, a bank of transients for the operations, a continuous filtered-noise
 * bed for friction while something is dragged, and a resolving interval at
 * ignition. Zero bytes of assets, and every voice can follow live scene state.
 *
 * It is an instrument, not a soundtrack. Each voice belongs to one physical
 * event, the room tone tracks charge and the current law, and nothing plays
 * itself.
 *
 * Rules this module keeps:
 * - Nothing is created until the visitor asks for it. Browsers block audio
 *   without a gesture, and starting a context on load would be hostile even
 *   where it is allowed.
 * - It is independent of `prefers-reduced-motion`. Someone who cannot tolerate
 *   motion may still want sound, and vice versa; conflating the two takes a
 *   choice away.
 * - A hidden tab is silent, and the whole graph is torn down on opt-out.
 * - Every transient is rate-limited. A pointer sweeping a shell fires dozens of
 *   hover events a second, and an unthrottled click per event is a buzzsaw.
 */

/** Deliberately low: this is a room, not a soundtrack. */
const ROOM_GAIN = 0.035
const IGNITION_GAIN = 0.05
/** Friction never reaches the room's own level — it is a texture under it. */
const FRICTION_GAIN = 0.05

/** Minimum gap between two transients of the same voice, in seconds. */
const HOVER_THROTTLE = 0.055
const TICK_THROTTLE = 0.04

/** Pitches for module locks — a rising minor triad, one voice per module. */
const LOCK_PITCHES = [220, 261.63, 329.63, 392]
/** Law intervals: root, fifth, minor seventh — vacuum, viscous, chaos. */
const LAW_PITCHES = [330, 247.5, 293.33]

export interface ReactorSound {
  stop: () => void
  hover: () => void
  tick: () => void
  lock: (index?: number) => void
  law: (index?: number) => void
  whoosh: () => void
  uplink: () => void
  deny: () => void
  level: () => number
  /** Legacy name kept so existing call sites keep working. */
  pulse: () => void
}

const noiseBuffer = (context: AudioContext, seconds: number, shaped: boolean) => {
  const length = Math.floor(context.sampleRate * seconds)
  const buffer = context.createBuffer(1, length, context.sampleRate)
  const data = buffer.getChannelData(0)
  for (let index = 0; index < length; index += 1) {
    const noise = Math.random() * 2 - 1
    if (!shaped) {
      data[index] = noise
      continue
    }
    // Decaying white noise: the envelope is baked in so a transient needs no
    // scheduled gain ramp of its own.
    const decay = 1 - index / length
    data[index] = noise * decay * decay
  }
  return buffer
}

export const startReactorSound = (): ReactorSound => {
  const context = new AudioContext()

  const master = context.createGain()
  master.gain.value = 0

  /**
   * One analyser on the master bus. The scene asks for `level()` once a frame to
   * drive `uAudio`, so the visitor can *see* what they hear — the lattice and
   * the conduits brighten on the transients rather than on a fake envelope.
   */
  const analyser = context.createAnalyser()
  analyser.fftSize = 32
  analyser.smoothingTimeConstant = 0.6
  const levelBuffer = new Uint8Array(analyser.fftSize)

  master.connect(analyser)
  master.connect(context.destination)

  // Room tone: a low fifth, slightly detuned so it beats rather than sits still.
  const room = context.createGain()
  room.gain.value = ROOM_GAIN
  const roomFilter = context.createBiquadFilter()
  roomFilter.type = 'lowpass'
  roomFilter.frequency.value = 220
  roomFilter.Q.value = 0.6
  room.connect(roomFilter).connect(master)

  const drones = [55, 82.5].map((frequency, index) => {
    const oscillator = context.createOscillator()
    oscillator.type = 'sine'
    oscillator.frequency.value = frequency
    oscillator.detune.value = index === 0 ? -4 : 6
    const gain = context.createGain()
    gain.gain.value = index === 0 ? 1 : 0.45
    oscillator.connect(gain).connect(room)
    oscillator.start()
    return { oscillator, gain }
  })

  // A very slow swell so the room breathes instead of humming flat.
  const breath = context.createOscillator()
  breath.type = 'sine'
  breath.frequency.value = 0.07
  const breathDepth = context.createGain()
  breathDepth.gain.value = ROOM_GAIN * 0.4
  breath.connect(breathDepth).connect(room.gain)
  breath.start()

  // Ignition: a fifth above the drone, opened only by the final chapter.
  const ignition = context.createGain()
  ignition.gain.value = 0
  ignition.connect(master)
  const ignitionVoice = context.createOscillator()
  ignitionVoice.type = 'triangle'
  ignitionVoice.frequency.value = 165
  ignitionVoice.connect(ignition)
  ignitionVoice.start()
  // A second partial an octave up, opened later than the fundamental, so the
  // finale grows a harmonic instead of just getting louder.
  const ignitionUpper = context.createGain()
  ignitionUpper.gain.value = 0
  ignitionUpper.connect(master)
  const ignitionUpperVoice = context.createOscillator()
  ignitionUpperVoice.type = 'sine'
  ignitionUpperVoice.frequency.value = 330
  ignitionUpperVoice.connect(ignitionUpper)
  ignitionUpperVoice.start()

  /**
   * Friction.
   *
   * A looping noise source whose cutoff and gain follow how fast the held object
   * is moving — read straight off `reactorControl.heldSpeed`, which the core
   * writes every frame. Friction is a continuous quantity, not an event, so it
   * has no voice method to call. Scheduling a transient per frame would both cost allocations and
   * sound like gravel; one continuous voice that opens and closes is what reads
   * as a mass moving through a medium.
   */
  const frictionSource = context.createBufferSource()
  frictionSource.buffer = noiseBuffer(context, 2, false)
  frictionSource.loop = true
  const frictionFilter = context.createBiquadFilter()
  frictionFilter.type = 'bandpass'
  frictionFilter.frequency.value = 320
  frictionFilter.Q.value = 0.9
  const frictionGain = context.createGain()
  frictionGain.gain.value = 0
  frictionSource.connect(frictionFilter).connect(frictionGain).connect(master)
  frictionSource.start()

  const transient = noiseBuffer(context, 0.4, true)
  const shortTransient = noiseBuffer(context, 0.09, true)

  // Fade in, so switching sound on is not a click.
  master.gain.linearRampToValueAtTime(1, context.currentTime + 0.9)

  const running = () => context.state === 'running'

  /** Shared transient factory — one buffer source through a band and a gain. */
  const burst = (
    buffer: AudioBuffer,
    frequency: number,
    q: number,
    gain: number,
    type: BiquadFilterType = 'bandpass',
  ) => {
    if (!running()) return
    const source = context.createBufferSource()
    source.buffer = buffer
    const band = context.createBiquadFilter()
    band.type = type
    band.frequency.value = frequency
    band.Q.value = q
    const level = context.createGain()
    level.gain.value = gain
    source.connect(band).connect(level).connect(master)
    source.start()
  }

  /** Pitched voice with an exponential tail — used for locks and intervals. */
  const tone = (
    frequency: number,
    gain: number,
    seconds: number,
    type: OscillatorType = 'triangle',
    detune = 0,
  ) => {
    if (!running()) return
    const now = context.currentTime
    const oscillator = context.createOscillator()
    oscillator.type = type
    oscillator.frequency.value = frequency
    oscillator.detune.value = detune
    const level = context.createGain()
    level.gain.setValueAtTime(0.0001, now)
    level.gain.exponentialRampToValueAtTime(gain, now + 0.012)
    level.gain.exponentialRampToValueAtTime(0.0001, now + seconds)
    oscillator.connect(level).connect(master)
    oscillator.start(now)
    oscillator.stop(now + seconds + 0.05)
  }

  let lastHover = -1
  let lastTick = -1

  let frame = 0
  const follow = () => {
    const power = livePowerFor(sceneState.build)
    const now = context.currentTime
    // `setTargetAtTime` smooths automatically, so scroll velocity cannot produce
    // zipper noise on the filter.
    const heat = liveLaw.heat
    // The law opens the room. CHAOS is not a different sound, it is the same
    // room with the lid off — which is exactly what the visuals do too.
    roomFilter.frequency.setTargetAtTime(
      220 + sceneState.build * 260 + heat * 900,
      now,
      0.3,
    )
    roomFilter.Q.setTargetAtTime(0.6 + heat * 2.4, now, 0.4)
    ignition.gain.setTargetAtTime(power * IGNITION_GAIN, now, 0.4)
    ignitionUpper.gain.setTargetAtTime(
      power * power * IGNITION_GAIN * 0.55,
      now,
      0.6,
    )

    // Friction only exists while something is genuinely held and moving.
    const held = reactorControl.held ? reactorControl.heldSpeed : 0
    frictionGain.gain.setTargetAtTime(held * FRICTION_GAIN, now, 0.08)
    frictionFilter.frequency.setTargetAtTime(240 + held * 1400, now, 0.1)

    frame = requestAnimationFrame(follow)
  }
  frame = requestAnimationFrame(follow)

  const handleVisibility = () => {
    if (document.visibilityState === 'hidden') {
      void context.suspend()
      return
    }
    void context.resume()
  }
  document.addEventListener('visibilitychange', handleVisibility)

  const lock = (index = 0) => {
    const pitch = LOCK_PITCHES[Math.abs(index) % LOCK_PITCHES.length]
    // Two halves: the impact (noise) and the body (pitch). Either alone reads as
    // a UI beep; together they read as a part seating in a socket.
    burst(transient, pitch * 2.4, 1.4, 0.055)
    tone(pitch, 0.045, 0.42)
  }

  return {
    hover: () => {
      const now = context.currentTime
      if (now - lastHover < HOVER_THROTTLE) return
      lastHover = now
      burst(shortTransient, 1600, 3.2, 0.028)
    },
    tick: () => {
      const now = context.currentTime
      if (now - lastTick < TICK_THROTTLE) return
      lastTick = now
      burst(shortTransient, 3200, 4.5, 0.022, 'highpass')
    },
    lock,
    // `pulse` predates the voice bank; module focus still calls it.
    pulse: () => lock(0),
    law: (index = 0) => {
      const pitch = LAW_PITCHES[Math.abs(index) % LAW_PITCHES.length]
      tone(pitch, 0.03, 0.55, 'sine')
      tone(pitch * 1.5, 0.018, 0.7, 'sine', 4)
    },
    whoosh: () => {
      if (!running()) return
      burst(transient, 520, 0.7, 0.04, 'lowpass')
      // A single short delay tap is enough to place the sound down the corridor.
      window.setTimeout(() => burst(transient, 900, 1.2, 0.02), 40)
    },
    uplink: () => {
      // The finale interval, arriving as a chord rather than as one more beep.
      tone(165, 0.05, 1.8)
      tone(247.5, 0.04, 2.1, 'sine', -3)
      tone(330, 0.03, 2.6, 'sine', 5)
      burst(transient, 1200, 0.8, 0.05)
    },
    deny: () => {
      tone(110, 0.03, 0.22, 'square')
    },
    level: () => {
      if (!running()) return 0
      analyser.getByteTimeDomainData(levelBuffer)
      let sum = 0
      for (let index = 0; index < levelBuffer.length; index += 1) {
        const sample = (levelBuffer[index] - 128) / 128
        sum += sample * sample
      }
      // The bus sits far below unity, so a raw RMS never leaves the noise floor.
      return Math.min(1, Math.sqrt(sum / levelBuffer.length) * 12)
    },
    stop: () => {
      cancelAnimationFrame(frame)
      document.removeEventListener('visibilitychange', handleVisibility)
      master.gain.setTargetAtTime(0, context.currentTime, 0.15)
      // Let the fade finish before tearing the graph down, otherwise stopping
      // produces the click that fading in was there to avoid.
      window.setTimeout(() => {
        drones.forEach(({ oscillator }) => oscillator.stop())
        breath.stop()
        ignitionVoice.stop()
        ignitionUpperVoice.stop()
        frictionSource.stop()
        void context.close()
      }, 400)
    },
  }
}
