import { liveLaw, reactorControl } from '../scene/control/reactorControl'
import { livePowerFor, sceneState } from '../scene/sceneState'

/**
 * The reactor's sound, synthesised rather than downloaded.
 *
 * Shipping room tone and transients as audio files would have cost a couple of
 * hundred kilobytes for a layer most visitors never turn on. Everything here is
 * generated by Web Audio instead: two detuned oscillators through a low-pass for
 * the room, a bank of transients for the operations, a continuous filtered-noise
 * bed for friction while something is dragged, and a resolving interval at
 * ignition. Zero bytes of assets, and every voice can follow live scene state.
 *
 * It is an instrument, not a soundtrack. Each voice belongs to one physical
 * event, the room tone tracks charge and the current law, and nothing plays
 * itself.
 *
 * Rules this module keeps:
 * - Nothing is created until the visitor asks for it. Browsers block audio
 *   without a gesture, and starting a context on load would be hostile even
 *   where it is allowed.
 * - It is independent of `prefers-reduced-motion`. Someone who cannot tolerate
 *   motion may still want sound, and vice versa; conflating the two takes a
 *   choice away.
 * - A hidden tab is silent, and the whole graph is torn down on opt-out.
 * - Every transient is rate-limited. A pointer sweeping a shell fires dozens of
 *   hover events a second, and an unthrottled click per event is a buzzsaw.
 *
 * Two more voices layer on top of the base instrument:
 * - Every burst and tone panned to the pointer's screen position, so the room
 *   has a left/right side instead of every event arriving dead centre.
 * - `hover`/`tick`/`lock`/`law` read the operator's active mode and pick a
 *   different filter/oscillator character per mode, so `wire`, `crt`, and
 *   `ghost` are a different instrument, not the same click retuned. Overclock
 *   instead drives the whole master bus through a soft-clip stage that grows
 *   with heat — the room distorting, not one more voice.
 */

/** Deliberately low: this is a room, not a soundtrack. */
const ROOM_GAIN = 0.035
const IGNITION_GAIN = 0.05
/** Friction never reaches the room's own level — it is a texture under it. */
const FRICTION_GAIN = 0.05

/** Minimum gap between two transients of the same voice, in seconds. */
const HOVER_THROTTLE = 0.055
const TICK_THROTTLE = 0.04

/** Pitches for module locks — a rising minor triad, one voice per module. */
const LOCK_PITCHES = [220, 261.63, 329.63, 392]
/** Law intervals: root, fifth, minor seventh — vacuum, viscous, chaos. */
const LAW_PITCHES = [330, 247.5, 293.33]

export interface ReactorSound {
  stop: () => void
  hover: () => void
  tick: () => void
  lock: (index?: number) => void
  law: (index?: number) => void
  whoosh: () => void
  uplink: () => void
  deny: () => void
  level: () => number
  /** Legacy name kept so existing call sites keep working. */
  pulse: () => void
}

const noiseBuffer = (context: AudioContext, seconds: number, shaped: boolean) => {
  const length = Math.floor(context.sampleRate * seconds)
  const buffer = context.createBuffer(1, length, context.sampleRate)
  const data = buffer.getChannelData(0)
  for (let index = 0; index < length; index += 1) {
    const noise = Math.random() * 2 - 1
    if (!shaped) {
      data[index] = noise
      continue
    }
    // Decaying white noise: the envelope is baked in so a transient needs no
    // scheduled gain ramp of its own.
    const decay = 1 - index / length
    data[index] = noise * decay * decay
  }
  return buffer
}

export const startReactorSound = (): ReactorSound => {
  const context = new AudioContext()

  const master = context.createGain()
  master.gain.value = 0

  /**
   * One analyser on the master bus. The scene asks for `level()` once a frame to
   * drive `uAudio`, so the visitor can *see* what they hear — the lattice and
   * the conduits brighten on the transients rather than on a fake envelope.
   */
  const analyser = context.createAnalyser()
  analyser.fftSize = 32
  analyser.smoothingTimeConstant = 0.6
  const levelBuffer = new Uint8Array(analyser.fftSize)

  /**
   * Overclock's own instrument: a soft-clip stage on the master bus, silent
   * (identity curve) everywhere else. It grows with heat rather than snapping
   * on, so the room saturates the same way its filter opens up.
   */
  const drive = context.createWaveShaper()
  drive.oversample = '2x'
  let driveAmount = -1
  const driveCurve = (amount: number) => {
    const samples = 256
    const curve = new Float32Array(samples)
    const k = 1 + amount * 6
    const norm = Math.tanh(k) || 1
    for (let index = 0; index < samples; index += 1) {
      const x = (index / (samples - 1)) * 2 - 1
      curve[index] = Math.tanh(x * k) / norm
    }
    return curve
  }
  drive.curve = driveCurve(0)

  master.connect(drive)
  drive.connect(analyser)
  drive.connect(context.destination)

  // Room tone: a low fifth, slightly detuned so it beats rather than sits still.
  const room = context.createGain()
  room.gain.value = ROOM_GAIN
  const roomFilter = context.createBiquadFilter()
  roomFilter.type = 'lowpass'
  roomFilter.frequency.value = 220
  roomFilter.Q.value = 0.6
  /*
   * The vacuum filter.
   *
   * A highpass, in series after the room's lowpass, whose corner rises with the
   * law's `airless`. Under VACUUM it climbs past the drones and takes the body of
   * the room with it, leaving a thin ring where a fifth used to be — the sound of
   * a medium that is not there. Under the other two laws it sits at 20 Hz and is
   * audibly nothing at all, which is why it can be left in the graph
   * unconditionally rather than connected and disconnected.
   */
  const airFilter = context.createBiquadFilter()
  airFilter.type = 'highpass'
  airFilter.frequency.value = 20
  airFilter.Q.value = 0.5
  room.connect(roomFilter).connect(airFilter).connect(master)

  const drones = [55, 82.5].map((frequency, index) => {
    const oscillator = context.createOscillator()
    oscillator.type = 'sine'
    oscillator.frequency.value = frequency
    oscillator.detune.value = index === 0 ? -4 : 6
    const gain = context.createGain()
    gain.gain.value = index === 0 ? 1 : 0.45
    oscillator.connect(gain).connect(room)
    oscillator.start()
    return { oscillator, gain }
  })

  // A very slow swell so the room breathes instead of humming flat.
  const breath = context.createOscillator()
  breath.type = 'sine'
  breath.frequency.value = 0.07
  const breathDepth = context.createGain()
  breathDepth.gain.value = ROOM_GAIN * 0.4
  breath.connect(breathDepth).connect(room.gain)
  breath.start()

  // Ignition: a fifth above the drone, opened only by the final chapter.
  const ignition = context.createGain()
  ignition.gain.value = 0
  ignition.connect(master)
  const ignitionVoice = context.createOscillator()
  ignitionVoice.type = 'triangle'
  ignitionVoice.frequency.value = 165
  ignitionVoice.connect(ignition)
  ignitionVoice.start()
  // A second partial an octave up, opened later than the fundamental, so the
  // finale grows a harmonic instead of just getting louder.
  const ignitionUpper = context.createGain()
  ignitionUpper.gain.value = 0
  ignitionUpper.connect(master)
  const ignitionUpperVoice = context.createOscillator()
  ignitionUpperVoice.type = 'sine'
  ignitionUpperVoice.frequency.value = 330
  ignitionUpperVoice.connect(ignitionUpper)
  ignitionUpperVoice.start()
  // A third partial, detuned a few cents off the fundamental, so full charge
  // thickens into a beating unison instead of just getting louder.
  const ignitionDetune = context.createGain()
  ignitionDetune.gain.value = 0
  ignitionDetune.connect(master)
  const ignitionDetuneVoice = context.createOscillator()
  ignitionDetuneVoice.type = 'triangle'
  ignitionDetuneVoice.frequency.value = 165
  ignitionDetuneVoice.detune.value = 9
  ignitionDetuneVoice.connect(ignitionDetune)
  ignitionDetuneVoice.start()

  /**
   * Friction.
   *
   * A looping noise source whose cutoff and gain follow how fast the held object
   * is moving — read straight off `reactorControl.heldSpeed`, which the core
   * writes every frame. Friction is a continuous quantity, not an event, so it
   * has no voice method to call. Scheduling a transient per frame would both cost allocations and
   * sound like gravel; one continuous voice that opens and closes is what reads
   * as a mass moving through a medium.
   */
  const frictionSource = context.createBufferSource()
  frictionSource.buffer = noiseBuffer(context, 2, false)
  frictionSource.loop = true
  const frictionFilter = context.createBiquadFilter()
  frictionFilter.type = 'bandpass'
  frictionFilter.frequency.value = 320
  frictionFilter.Q.value = 0.9
  const frictionGain = context.createGain()
  frictionGain.gain.value = 0
  frictionSource.connect(frictionFilter).connect(frictionGain).connect(master)
  frictionSource.start()

  const transient = noiseBuffer(context, 0.4, true)
  const shortTransient = noiseBuffer(context, 0.09, true)

  // Fade in, so switching sound on is not a click.
  master.gain.linearRampToValueAtTime(1, context.currentTime + 0.9)

  const running = () => context.state === 'running'

  /**
   * The pointer's screen position, read fresh per voice so a hover on the left
   * edge and a lock on the right edge land in different places — no plumbing
   * beyond the tracker that already exists for pointer-driven scene state.
   */
  const pointerPan = () =>
    Math.max(-1, Math.min(1, sceneState.pointerX || 0))

  /** Shared transient factory — one buffer source through a band and a gain. */
  const burst = (
    buffer: AudioBuffer,
    frequency: number,
    q: number,
    gain: number,
    type: BiquadFilterType = 'bandpass',
  ) => {
    if (!running()) return
    const source = context.createBufferSource()
    source.buffer = buffer
    const band = context.createBiquadFilter()
    band.type = type
    band.frequency.value = frequency
    band.Q.value = q
    const level = context.createGain()
    level.gain.value = gain
    const pan = context.createStereoPanner()
    pan.pan.value = pointerPan()
    source.connect(band).connect(level).connect(pan).connect(master)
    source.start()
  }

  /** Pitched voice with an exponential tail — used for locks and intervals. */
  const tone = (
    frequency: number,
    gain: number,
    seconds: number,
    type: OscillatorType = 'triangle',
    detune = 0,
  ) => {
    if (!running()) return
    const now = context.currentTime
    const oscillator = context.createOscillator()
    oscillator.type = type
    oscillator.frequency.value = frequency
    oscillator.detune.value = detune
    const level = context.createGain()
    level.gain.setValueAtTime(0.0001, now)
    level.gain.exponentialRampToValueAtTime(gain, now + 0.012)
    level.gain.exponentialRampToValueAtTime(0.0001, now + seconds)
    const pan = context.createStereoPanner()
    pan.pan.value = pointerPan()
    oscillator.connect(level).connect(pan).connect(master)
    oscillator.start(now)
    oscillator.stop(now + seconds + 0.05)
  }

  let lastHover = -1
  let lastTick = -1

  let frame = 0
  const follow = () => {
    const power = livePowerFor(sceneState.build)
    const now = context.currentTime
    // `setTargetAtTime` smooths automatically, so scroll velocity cannot produce
    // zipper noise on the filter.
    const heat = liveLaw.heat
    const airless = liveLaw.airless
    const swallow = sceneState.swallow
    // The law opens the room. CHAOS is not a different sound, it is the same
    // room with the lid off — which is exactly what the visuals do too.
    roomFilter.frequency.setTargetAtTime(
      220 + sceneState.build * 260 + heat * 900,
      now,
      0.3,
    )
    roomFilter.Q.setTargetAtTime(0.6 + heat * 2.4, now, 0.4)
    /*
     * VACUUM lifts the floor out of the room. 20 Hz is inaudible; 320 Hz is above
     * both drones, so the fundamental and the fifth are simply gone and what is
     * left is the top of the signal chain — which is the point.
     */
    airFilter.frequency.setTargetAtTime(20 + airless * 300, now, 0.45)
    airFilter.Q.setTargetAtTime(0.5 + airless * 1.6, now, 0.5)
    // And the body itself thins: filtering alone would still leave a full-level
    // room with its bass removed, which sounds like a small speaker, not a vacuum.
    room.gain.setTargetAtTime(ROOM_GAIN * (1 - airless * 0.55), now, 0.5)

    /*
     * The swallow drags the room's pitch down with it.
     *
     * A falling fundamental is what the ending sounds like from the inside: the
     * drones glide down roughly a fifth as the portal takes the corridor in, and
     * come straight back up if the visitor scrolls out again, because — like
     * every other layer of that ending — this is a function of scroll position
     * and not a triggered slide.
     */
    drones.forEach((drone, index) => {
      const base = index === 0 ? 55 : 82.5
      drone.oscillator.frequency.setTargetAtTime(
        base * (1 - swallow * 0.34),
        now,
        0.25,
      )
    })
    ignition.gain.setTargetAtTime(power * IGNITION_GAIN, now, 0.4)
    ignitionUpper.gain.setTargetAtTime(
      power * power * IGNITION_GAIN * 0.55,
      now,
      0.6,
    )
    ignitionDetune.gain.setTargetAtTime(
      power * IGNITION_GAIN * 0.5,
      now,
      0.4,
    )

    // Friction only exists while something is genuinely held and moving.
    const held = reactorControl.held ? reactorControl.heldSpeed : 0
    frictionGain.gain.setTargetAtTime(held * FRICTION_GAIN, now, 0.08)
    frictionFilter.frequency.setTargetAtTime(240 + held * 1400, now, 0.1)

    // Overclock is the room saturating, not a new voice — the curve only
    // regenerates when the target has actually moved, so idle frames cost
    // nothing.
    /*
     * Saturation follows the law as well as the mode.
     *
     * The drive bus used to open only under the OVERCLOCK mode, which meant CHAOS
     * — the law whose entire character is a room being pushed past what it can
     * carry — sounded identical to VISCOUS unless the visitor also found a hidden
     * key. The law is the loud one; the mode adds to it.
     */
    const targetDrive = Math.min(
      1,
      heat * 0.62 + (reactorControl.modes.overclock ? 0.38 : 0),
    )
    if (Math.abs(targetDrive - driveAmount) > 0.03) {
      driveAmount = targetDrive
      drive.curve = driveCurve(driveAmount)
    }

    frame = requestAnimationFrame(follow)
  }
  frame = requestAnimationFrame(follow)

  const handleVisibility = () => {
    if (document.visibilityState === 'hidden') {
      void context.suspend()
      return
    }
    void context.resume()
  }
  document.addEventListener('visibilitychange', handleVisibility)

  /**
   * `wire`/`crt`/`ghost` each retune the four short voices below into a
   * different instrument rather than a different pitch. `overclock` is
   * excluded — it already has its own instrument, the drive bus in `follow`.
   * Priority favours the mode most visually dominant when stacked.
   */
  type VoiceMode = 'default' | 'wire' | 'crt' | 'ghost'
  const activeVoiceMode = (): VoiceMode => {
    if (reactorControl.modes.ghost) return 'ghost'
    if (reactorControl.modes.crt) return 'crt'
    if (reactorControl.modes.wire) return 'wire'
    return 'default'
  }
  /** CRT's echo tap — one delayed repeat, the same trick `whoosh` already uses. */
  const echoTap = (buffer: AudioBuffer, frequency: number, gain: number) => {
    window.setTimeout(() => burst(buffer, frequency, 3, gain, 'bandpass'), 35)
  }

  const lock = (index = 0) => {
    const pitch = LOCK_PITCHES[Math.abs(index) % LOCK_PITCHES.length]
    // Two halves: the impact (noise) and the body (pitch). Either alone reads as
    // a UI beep; together they read as a part seating in a socket.
    switch (activeVoiceMode()) {
      case 'wire':
        burst(transient, pitch * 3.2, 2.2, 0.045, 'highpass')
        tone(pitch * 2, 0.03, 0.28, 'sine')
        break
      case 'crt':
        burst(transient, pitch * 2.4, 1.4, 0.05)
        tone(pitch, 0.045, 0.42, 'square', 2)
        echoTap(shortTransient, pitch * 3, 0.014)
        break
      case 'ghost':
        burst(transient, pitch * 1.2, 0.8, 0.05, 'lowpass')
        tone(pitch * 0.5, 0.05, 0.9, 'sine', -12)
        break
      default:
        burst(transient, pitch * 2.4, 1.4, 0.055)
        tone(pitch, 0.045, 0.42)
    }
  }

  return {
    hover: () => {
      const now = context.currentTime
      if (now - lastHover < HOVER_THROTTLE) return
      lastHover = now
      switch (activeVoiceMode()) {
        case 'wire':
          burst(shortTransient, 2600, 5, 0.024, 'highpass')
          break
        case 'crt':
          burst(shortTransient, 1600, 3.2, 0.026)
          echoTap(shortTransient, 2100, 0.012)
          break
        case 'ghost':
          burst(shortTransient, 900, 2, 0.03, 'lowpass')
          break
        default:
          burst(shortTransient, 1600, 3.2, 0.028)
      }
    },
    tick: () => {
      const now = context.currentTime
      if (now - lastTick < TICK_THROTTLE) return
      lastTick = now
      switch (activeVoiceMode()) {
        case 'wire':
          burst(shortTransient, 4200, 6, 0.02, 'highpass')
          break
        case 'crt':
          burst(shortTransient, 3200, 4.5, 0.02)
          echoTap(shortTransient, 3600, 0.01)
          break
        case 'ghost':
          burst(shortTransient, 1800, 2.5, 0.024, 'lowpass')
          break
        default:
          burst(shortTransient, 3200, 4.5, 0.022, 'highpass')
      }
    },
    lock,
    // `pulse` predates the voice bank; module focus still calls it.
    pulse: () => lock(0),
    law: (index = 0) => {
      const pitch = LAW_PITCHES[Math.abs(index) % LAW_PITCHES.length]
      switch (activeVoiceMode()) {
        case 'wire':
          tone(pitch * 2, 0.025, 0.4, 'sine')
          tone(pitch * 3, 0.014, 0.5, 'sine', 7)
          break
        case 'crt':
          tone(pitch, 0.03, 0.5, 'square', 2)
          tone(pitch * 1.5, 0.016, 0.6, 'square', -2)
          break
        case 'ghost':
          tone(pitch * 0.5, 0.032, 0.9, 'sine', -14)
          tone(pitch * 0.75, 0.02, 1.1, 'sine', 14)
          break
        default:
          tone(pitch, 0.03, 0.55, 'sine')
          tone(pitch * 1.5, 0.018, 0.7, 'sine', 4)
      }
    },
    whoosh: () => {
      if (!running()) return
      burst(transient, 520, 0.7, 0.04, 'lowpass')
      // A single short delay tap is enough to place the sound down the corridor.
      window.setTimeout(() => burst(transient, 900, 1.2, 0.02), 40)
    },
    uplink: () => {
      // The finale interval, arriving as a chord rather than as one more beep.
      tone(165, 0.05, 1.8)
      tone(247.5, 0.04, 2.1, 'sine', -3)
      tone(330, 0.03, 2.6, 'sine', 5)
      burst(transient, 1200, 0.8, 0.05)
    },
    deny: () => {
      tone(110, 0.03, 0.22, 'square')
    },
    level: () => {
      if (!running()) return 0
      analyser.getByteTimeDomainData(levelBuffer)
      let sum = 0
      for (let index = 0; index < levelBuffer.length; index += 1) {
        const sample = (levelBuffer[index] - 128) / 128
        sum += sample * sample
      }
      // The bus sits far below unity, so a raw RMS never leaves the noise floor.
      return Math.min(1, Math.sqrt(sum / levelBuffer.length) * 12)
    },
    stop: () => {
      cancelAnimationFrame(frame)
      document.removeEventListener('visibilitychange', handleVisibility)
      master.gain.setTargetAtTime(0, context.currentTime, 0.15)
      // Let the fade finish before tearing the graph down, otherwise stopping
      // produces the click that fading in was there to avoid.
      window.setTimeout(() => {
        drones.forEach(({ oscillator }) => oscillator.stop())
        breath.stop()
        ignitionVoice.stop()
        ignitionUpperVoice.stop()
        ignitionDetuneVoice.stop()
        frictionSource.stop()
        void context.close()
      }, 400)
    },
  }
}
